service: medium-readme-stats

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  profile: medium-readme-stats
  logRetentionInDays: 14
  architecture: arm64
  memorySize: 128
  timeout: 15
  versionFunctions: false
  stage: prod
  httpApi:
    cors: true
  logs:
    lambda:
      logFormat: JSON
      applicationLogLevel: INFO
      systemLogLevel: INFO

functions:
  v1GetRecentPost:
    handler: handler.handler
    events:
      - httpApi:
          path: /v1/post
          method: get

build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - aws-lambda

package:
  exclude:
    - tests/**

resources:
  Resources:
    CustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      Properties:
        DomainName: medium.junah.dev
        DomainNameConfigurations:
          - CertificateArn: arn:aws:acm:ap-northeast-2:491558244397:certificate/6679a127-5198-4119-a9ef-087240f267cd
            EndpointType: REGIONAL
            SecurityPolicy: TLS_1_2

    ApiMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
        ApiId:
          Ref: HttpApi
        DomainName:
          Ref: CustomDomain
        Stage: $default
